piVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: <your-ecr-repo>:latest
        env:
        - name: OLLAMA_NUM_PARALLEL
          value: "2"
        ports:
        - containerPort: 11434
